/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageSlugRouteImport } from './routes/$pageSlug'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as GetAQuoteRouteImport } from './routes/get-a-quote'
import { Route as HepaFiltrationSystemForOperationTheatreRouteImport } from './routes/hepa-filtration-system-for-operation-theatre'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as ModularOtCeilingRouteImport } from './routes/modular-ot-ceiling'
import { Route as ModularOtDoorsRouteImport } from './routes/modular-ot-doors'
import { Route as ModularOtWallPanelsRouteImport } from './routes/modular-ot-wall-panels'
import { Route as OperationTheatreElectricalSystemRouteImport } from './routes/operation-theatre-electrical-system'
import { Route as OperationTheatreHvacSystemRouteImport } from './routes/operation-theatre-hvac-system'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as AdminDashboardRouteImport } from './routes/admin_.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as MedicalGasPipelineManufacturerStateRouteImport } from './routes/medical-gas-pipeline-manufacturer.$state'
import { Route as MedicalGasPipelineManufacturersInStateRouteImport } from './routes/medical-gas-pipeline-manufacturers-in.$state'
import { Route as ModularOperationTheatreManufacturerStateRouteImport } from './routes/modular-operation-theatre-manufacturer.$state'
import { Route as ModularOperationTheatreManufacturersInStateRouteImport } from './routes/modular-operation-theatre-manufacturers-in.$state'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as BlogCategoryCategoryRouteImport } from './routes/blog.category.$category'
import { Route as ProductsModularOperationTheatreVariantRouteImport } from './routes/products.modular-operation-theatre.$variant'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageSlugRoute = PageSlugRouteImport.update({
  id: '/$pageSlug',
  path: '/$pageSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAQuoteRoute = GetAQuoteRouteImport.update({
  id: '/get-a-quote',
  path: '/get-a-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const HepaFiltrationSystemForOperationTheatreRoute =
  HepaFiltrationSystemForOperationTheatreRouteImport.update({
    id: '/hepa-filtration-system-for-operation-theatre',
    path: '/hepa-filtration-system-for-operation-theatre',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularOtCeilingRoute = ModularOtCeilingRouteImport.update({
  id: '/modular-ot-ceiling',
  path: '/modular-ot-ceiling',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularOtDoorsRoute = ModularOtDoorsRouteImport.update({
  id: '/modular-ot-doors',
  path: '/modular-ot-doors',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularOtWallPanelsRoute = ModularOtWallPanelsRouteImport.update({
  id: '/modular-ot-wall-panels',
  path: '/modular-ot-wall-panels',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationTheatreElectricalSystemRoute =
  OperationTheatreElectricalSystemRouteImport.update({
    id: '/operation-theatre-electrical-system',
    path: '/operation-theatre-electrical-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const OperationTheatreHvacSystemRoute =
  OperationTheatreHvacSystemRouteImport.update({
    id: '/operation-theatre-hvac-system',
    path: '/operation-theatre-hvac-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin_/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalGasPipelineManufacturerStateRoute =
  MedicalGasPipelineManufacturerStateRouteImport.update({
    id: '/medical-gas-pipeline-manufacturer/$state',
    path: '/medical-gas-pipeline-manufacturer/$state',
    getParentRoute: () => rootRouteImport,
  } as any)
const MedicalGasPipelineManufacturersInStateRoute =
  MedicalGasPipelineManufacturersInStateRouteImport.update({
    id: '/medical-gas-pipeline-manufacturers-in/$state',
    path: '/medical-gas-pipeline-manufacturers-in/$state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModularOperationTheatreManufacturerStateRoute =
  ModularOperationTheatreManufacturerStateRouteImport.update({
    id: '/modular-operation-theatre-manufacturer/$state',
    path: '/modular-operation-theatre-manufacturer/$state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ModularOperationTheatreManufacturersInStateRoute =
  ModularOperationTheatreManufacturersInStateRouteImport.update({
    id: '/modular-operation-theatre-manufacturers-in/$state',
    path: '/modular-operation-theatre-manufacturers-in/$state',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogCategoryCategoryRoute = BlogCategoryCategoryRouteImport.update({
  id: '/blog/category/$category',
  path: '/blog/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsModularOperationTheatreVariantRoute =
  ProductsModularOperationTheatreVariantRouteImport.update({
    id: '/products/modular-operation-theatre/$variant',
    path: '/products/modular-operation-theatre/$variant',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/hepa-filtration-system-for-operation-theatre': typeof HepaFiltrationSystemForOperationTheatreRoute
  '/locations': typeof LocationsRoute
  '/modular-ot-ceiling': typeof ModularOtCeilingRoute
  '/modular-ot-doors': typeof ModularOtDoorsRoute
  '/modular-ot-wall-panels': typeof ModularOtWallPanelsRoute
  '/operation-theatre-electrical-system': typeof OperationTheatreElectricalSystemRoute
  '/operation-theatre-hvac-system': typeof OperationTheatreHvacSystemRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/solutions': typeof SolutionsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/medical-gas-pipeline-manufacturer/$state': typeof MedicalGasPipelineManufacturerStateRoute
  '/medical-gas-pipeline-manufacturers-in/$state': typeof MedicalGasPipelineManufacturersInStateRoute
  '/modular-operation-theatre-manufacturer/$state': typeof ModularOperationTheatreManufacturerStateRoute
  '/modular-operation-theatre-manufacturers-in/$state': typeof ModularOperationTheatreManufacturersInStateRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/products/modular-operation-theatre/$variant': typeof ProductsModularOperationTheatreVariantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/hepa-filtration-system-for-operation-theatre': typeof HepaFiltrationSystemForOperationTheatreRoute
  '/locations': typeof LocationsRoute
  '/modular-ot-ceiling': typeof ModularOtCeilingRoute
  '/modular-ot-doors': typeof ModularOtDoorsRoute
  '/modular-ot-wall-panels': typeof ModularOtWallPanelsRoute
  '/operation-theatre-electrical-system': typeof OperationTheatreElectricalSystemRoute
  '/operation-theatre-hvac-system': typeof OperationTheatreHvacSystemRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/solutions': typeof SolutionsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/medical-gas-pipeline-manufacturer/$state': typeof MedicalGasPipelineManufacturerStateRoute
  '/medical-gas-pipeline-manufacturers-in/$state': typeof MedicalGasPipelineManufacturersInStateRoute
  '/modular-operation-theatre-manufacturer/$state': typeof ModularOperationTheatreManufacturerStateRoute
  '/modular-operation-theatre-manufacturers-in/$state': typeof ModularOperationTheatreManufacturersInStateRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog': typeof BlogIndexRoute
  '/products': typeof ProductsIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/products/modular-operation-theatre/$variant': typeof ProductsModularOperationTheatreVariantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$pageSlug': typeof PageSlugRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/get-a-quote': typeof GetAQuoteRoute
  '/hepa-filtration-system-for-operation-theatre': typeof HepaFiltrationSystemForOperationTheatreRoute
  '/locations': typeof LocationsRoute
  '/modular-ot-ceiling': typeof ModularOtCeilingRoute
  '/modular-ot-doors': typeof ModularOtDoorsRoute
  '/modular-ot-wall-panels': typeof ModularOtWallPanelsRoute
  '/operation-theatre-electrical-system': typeof OperationTheatreElectricalSystemRoute
  '/operation-theatre-hvac-system': typeof OperationTheatreHvacSystemRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap': typeof SitemapRoute
  '/solutions': typeof SolutionsRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/admin_/dashboard': typeof AdminDashboardRoute
  '/admin_/login': typeof AdminLoginRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/medical-gas-pipeline-manufacturer/$state': typeof MedicalGasPipelineManufacturerStateRoute
  '/medical-gas-pipeline-manufacturers-in/$state': typeof MedicalGasPipelineManufacturersInStateRoute
  '/modular-operation-theatre-manufacturer/$state': typeof ModularOperationTheatreManufacturerStateRoute
  '/modular-operation-theatre-manufacturers-in/$state': typeof ModularOperationTheatreManufacturersInStateRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/products/modular-operation-theatre/$variant': typeof ProductsModularOperationTheatreVariantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$pageSlug'
    | '/about'
    | '/admin'
    | '/contact'
    | '/disclaimer'
    | '/get-a-quote'
    | '/hepa-filtration-system-for-operation-theatre'
    | '/locations'
    | '/modular-ot-ceiling'
    | '/modular-ot-doors'
    | '/modular-ot-wall-panels'
    | '/operation-theatre-electrical-system'
    | '/operation-theatre-hvac-system'
    | '/privacy-policy'
    | '/reset-password'
    | '/search'
    | '/sitemap'
    | '/solutions'
    | '/terms-and-conditions'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/medical-gas-pipeline-manufacturer/$state'
    | '/medical-gas-pipeline-manufacturers-in/$state'
    | '/modular-operation-theatre-manufacturer/$state'
    | '/modular-operation-theatre-manufacturers-in/$state'
    | '/products/$slug'
    | '/blog/'
    | '/products/'
    | '/blog/category/$category'
    | '/products/modular-operation-theatre/$variant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$pageSlug'
    | '/about'
    | '/admin'
    | '/contact'
    | '/disclaimer'
    | '/get-a-quote'
    | '/hepa-filtration-system-for-operation-theatre'
    | '/locations'
    | '/modular-ot-ceiling'
    | '/modular-ot-doors'
    | '/modular-ot-wall-panels'
    | '/operation-theatre-electrical-system'
    | '/operation-theatre-hvac-system'
    | '/privacy-policy'
    | '/reset-password'
    | '/search'
    | '/sitemap'
    | '/solutions'
    | '/terms-and-conditions'
    | '/admin/dashboard'
    | '/admin/login'
    | '/blog/$slug'
    | '/medical-gas-pipeline-manufacturer/$state'
    | '/medical-gas-pipeline-manufacturers-in/$state'
    | '/modular-operation-theatre-manufacturer/$state'
    | '/modular-operation-theatre-manufacturers-in/$state'
    | '/products/$slug'
    | '/blog'
    | '/products'
    | '/blog/category/$category'
    | '/products/modular-operation-theatre/$variant'
  id:
    | '__root__'
    | '/'
    | '/$pageSlug'
    | '/about'
    | '/admin'
    | '/contact'
    | '/disclaimer'
    | '/get-a-quote'
    | '/hepa-filtration-system-for-operation-theatre'
    | '/locations'
    | '/modular-ot-ceiling'
    | '/modular-ot-doors'
    | '/modular-ot-wall-panels'
    | '/operation-theatre-electrical-system'
    | '/operation-theatre-hvac-system'
    | '/privacy-policy'
    | '/reset-password'
    | '/search'
    | '/sitemap'
    | '/solutions'
    | '/terms-and-conditions'
    | '/admin_/dashboard'
    | '/admin_/login'
    | '/blog/$slug'
    | '/medical-gas-pipeline-manufacturer/$state'
    | '/medical-gas-pipeline-manufacturers-in/$state'
    | '/modular-operation-theatre-manufacturer/$state'
    | '/modular-operation-theatre-manufacturers-in/$state'
    | '/products/$slug'
    | '/blog/'
    | '/products/'
    | '/blog/category/$category'
    | '/products/modular-operation-theatre/$variant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageSlugRoute: typeof PageSlugRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GetAQuoteRoute: typeof GetAQuoteRoute
  HepaFiltrationSystemForOperationTheatreRoute: typeof HepaFiltrationSystemForOperationTheatreRoute
  LocationsRoute: typeof LocationsRoute
  ModularOtCeilingRoute: typeof ModularOtCeilingRoute
  ModularOtDoorsRoute: typeof ModularOtDoorsRoute
  ModularOtWallPanelsRoute: typeof ModularOtWallPanelsRoute
  OperationTheatreElectricalSystemRoute: typeof OperationTheatreElectricalSystemRoute
  OperationTheatreHvacSystemRoute: typeof OperationTheatreHvacSystemRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapRoute: typeof SitemapRoute
  SolutionsRoute: typeof SolutionsRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MedicalGasPipelineManufacturerStateRoute: typeof MedicalGasPipelineManufacturerStateRoute
  MedicalGasPipelineManufacturersInStateRoute: typeof MedicalGasPipelineManufacturersInStateRoute
  ModularOperationTheatreManufacturerStateRoute: typeof ModularOperationTheatreManufacturerStateRoute
  ModularOperationTheatreManufacturersInStateRoute: typeof ModularOperationTheatreManufacturersInStateRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  BlogCategoryCategoryRoute: typeof BlogCategoryCategoryRoute
  ProductsModularOperationTheatreVariantRoute: typeof ProductsModularOperationTheatreVariantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageSlug': {
      id: '/$pageSlug'
      path: '/$pageSlug'
      fullPath: '/$pageSlug'
      preLoaderRoute: typeof PageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-a-quote': {
      id: '/get-a-quote'
      path: '/get-a-quote'
      fullPath: '/get-a-quote'
      preLoaderRoute: typeof GetAQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hepa-filtration-system-for-operation-theatre': {
      id: '/hepa-filtration-system-for-operation-theatre'
      path: '/hepa-filtration-system-for-operation-theatre'
      fullPath: '/hepa-filtration-system-for-operation-theatre'
      preLoaderRoute: typeof HepaFiltrationSystemForOperationTheatreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular-ot-ceiling': {
      id: '/modular-ot-ceiling'
      path: '/modular-ot-ceiling'
      fullPath: '/modular-ot-ceiling'
      preLoaderRoute: typeof ModularOtCeilingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular-ot-doors': {
      id: '/modular-ot-doors'
      path: '/modular-ot-doors'
      fullPath: '/modular-ot-doors'
      preLoaderRoute: typeof ModularOtDoorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular-ot-wall-panels': {
      id: '/modular-ot-wall-panels'
      path: '/modular-ot-wall-panels'
      fullPath: '/modular-ot-wall-panels'
      preLoaderRoute: typeof ModularOtWallPanelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operation-theatre-electrical-system': {
      id: '/operation-theatre-electrical-system'
      path: '/operation-theatre-electrical-system'
      fullPath: '/operation-theatre-electrical-system'
      preLoaderRoute: typeof OperationTheatreElectricalSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operation-theatre-hvac-system': {
      id: '/operation-theatre-hvac-system'
      path: '/operation-theatre-hvac-system'
      fullPath: '/operation-theatre-hvac-system'
      preLoaderRoute: typeof OperationTheatreHvacSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/dashboard': {
      id: '/admin_/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-gas-pipeline-manufacturer/$state': {
      id: '/medical-gas-pipeline-manufacturer/$state'
      path: '/medical-gas-pipeline-manufacturer/$state'
      fullPath: '/medical-gas-pipeline-manufacturer/$state'
      preLoaderRoute: typeof MedicalGasPipelineManufacturerStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-gas-pipeline-manufacturers-in/$state': {
      id: '/medical-gas-pipeline-manufacturers-in/$state'
      path: '/medical-gas-pipeline-manufacturers-in/$state'
      fullPath: '/medical-gas-pipeline-manufacturers-in/$state'
      preLoaderRoute: typeof MedicalGasPipelineManufacturersInStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular-operation-theatre-manufacturer/$state': {
      id: '/modular-operation-theatre-manufacturer/$state'
      path: '/modular-operation-theatre-manufacturer/$state'
      fullPath: '/modular-operation-theatre-manufacturer/$state'
      preLoaderRoute: typeof ModularOperationTheatreManufacturerStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular-operation-theatre-manufacturers-in/$state': {
      id: '/modular-operation-theatre-manufacturers-in/$state'
      path: '/modular-operation-theatre-manufacturers-in/$state'
      fullPath: '/modular-operation-theatre-manufacturers-in/$state'
      preLoaderRoute: typeof ModularOperationTheatreManufacturersInStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/category/$category': {
      id: '/blog/category/$category'
      path: '/blog/category/$category'
      fullPath: '/blog/category/$category'
      preLoaderRoute: typeof BlogCategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/modular-operation-theatre/$variant': {
      id: '/products/modular-operation-theatre/$variant'
      path: '/products/modular-operation-theatre/$variant'
      fullPath: '/products/modular-operation-theatre/$variant'
      preLoaderRoute: typeof ProductsModularOperationTheatreVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageSlugRoute: PageSlugRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  GetAQuoteRoute: GetAQuoteRoute,
  HepaFiltrationSystemForOperationTheatreRoute:
    HepaFiltrationSystemForOperationTheatreRoute,
  LocationsRoute: LocationsRoute,
  ModularOtCeilingRoute: ModularOtCeilingRoute,
  ModularOtDoorsRoute: ModularOtDoorsRoute,
  ModularOtWallPanelsRoute: ModularOtWallPanelsRoute,
  OperationTheatreElectricalSystemRoute: OperationTheatreElectricalSystemRoute,
  OperationTheatreHvacSystemRoute: OperationTheatreHvacSystemRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapRoute: SitemapRoute,
  SolutionsRoute: SolutionsRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  BlogSlugRoute: BlogSlugRoute,
  MedicalGasPipelineManufacturerStateRoute:
    MedicalGasPipelineManufacturerStateRoute,
  MedicalGasPipelineManufacturersInStateRoute:
    MedicalGasPipelineManufacturersInStateRoute,
  ModularOperationTheatreManufacturerStateRoute:
    ModularOperationTheatreManufacturerStateRoute,
  ModularOperationTheatreManufacturersInStateRoute:
    ModularOperationTheatreManufacturersInStateRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  BlogCategoryCategoryRoute: BlogCategoryCategoryRoute,
  ProductsModularOperationTheatreVariantRoute:
    ProductsModularOperationTheatreVariantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
